### ISSUE TITLE
Creación de Salones

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#11]
Opción para crear salones, esta opción está solamente habilitada para el administrador, se deben solicitar los siguientes datos: 

 *

**Comment by arias9306** [comment]
@lobo-93 por realizar los siguientes cambios en el formulario de creación y edición de salones

1. Cambiar Estado por un combo que sea activo e inactivo (la primera letra del campo en mayúscula)
2. Cambio el campo de Tipo por un combo que sea Salón o Auditorio

**Comment by arias9306** [comment]
@lobo-93 por favor agregar el * de campo obligatorio a los siguientes campos 

1. Codigo
2. Estado
3. Tipo

Ejemplo 

`<label class="col-sm-2 control-label">Estado: <span class="text-danger">*</span></label>`

**Comment by arias9306** [comment]
@lobo-93  por favor agregar la anotación de `@NotNull` a los campos requeridos en el modelo de salones

**Comment by JLancherosR** [comment]
@lobo-93 El campo bloque muestra que no es obligatorio pero cuando se deja vacío se genera un error.

**Comment by lobo-93** [comment]
ya se hizo correciones con respecto a los errores

**Comment by fredytellor** [comment]
Funciona correctamente
