### ISSUE TITLE
Edición de Salones

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#12]
Opción para editar un salón seleccionado, esta opción solo es valida para el administrador, se debe solicitar confirmación al usuario antes de editar el salón

**Comment by JLancherosR** [comment]
@lobo-93 Arreglar la opción editar porque al darle en guardar cambios, en vez de editar lo que hace es crear otro salón.

**Comment by JLancherosR** [comment]
@lobo-93 El campo bloque muestra que no es obligatorio pero cuando se deja vacío se genera un error.

**Comment by fredytellor** [comment]
funciona correctamente
