### ISSUE TITLE
Consulta de Salones

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#16]
Opción de consulta de salones, la información se debe de mostrar en una tabla con la siguiente información y debe de dar la opción de visualizar toda la información, validando el rol, si es una administrador lo puede editar de lo contrario solo puede ver la información sin editarla

**Comment by JLancherosR** [comment]
@lobo-93 A la información que muestra en la opción consulta, hay que corregir el estado, que salga en español e igual con editar por edit y eliminar por delete.

**Comment by fredytellor** [comment]
Funciona Bien
