### ISSUE TITLE
Creación de Caracteristica

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#28]

**Comment by JLancherosR** [comment]
@EDIJAI y @rcastellanos10 Revisar el lugar donde esta puesto el botón Guardar, debería ir a la derecha.

**Comment by lobo-93** [comment]
se pueden crear caracteristicas vacias, falta el mensaje de error

**Comment by lobo-93** [comment]
todo esta funcionando correctamente.
