### ISSUE TITLE
Inicio de sesión

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#3]
**Descripción**: Implementar el inicio de sesión para los usuarios registrados en el sistema 

**Criterios de Aceptación**
* Se deben validar que los usuarios existan en la base de datos y los datos sean correctos
* Mostrar mensajes de error informando al usuario si hay algún dato mal
* Mensajes:
  - Su usuario o contraseña son incorrectos

**Comment by EDIJAI** [comment]
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods

**Comment by fredytellor** [comment]
funciona bien
