### ISSUE TITLE
Creación de Programas

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#37]

**Comment by micrista** [comment]
@fredytellor  no se estan  mostrando los mensajes de error en el formulario de crear programas

**Comment by JLancherosR** [comment]
@fredytellor No esta creando programa, tampoco muestra los errores cuando hay un campo vacío y el botón guardar debe ir al lado derecho.

**Comment by JLancherosR** [comment]
Con @fredytellor solucionamos todos los errores de este módulo.

**Comment by JLancherosR** [comment]
La creación de programas funciona correctamente.
