### ISSUE TITLE
Creación de usuario

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#6]
Opción para la creación de nuevo usuarios en el sistema, está opción solo es la valida para el administrador

Información a solicitar del usuario: 
*

**Comment by arias9306** [comment]
@JLancherosR Por favor agregar el * de campo obligatorio a los siguientes campos

1. Primer Nombre
2. Primer Apellido
3. Correo
4. Código
5. Nro Identificación
6. Telefono
7. Password
8. Estado
9. Rol
10. Progama

Ejemplo 
`<label class="col-sm-2 control-label">Primer Nombre: <span class="text-danger">*</span></label>`

**Comment by JLancherosR** [comment]
@arias9306 Ya realice los cambios 1 y 3 que nos sugirió. Por favor revisar.

**Comment by JLancherosR** [comment]
@arias9306 Ya realice la actividad del asterisco en los campos obligatorios, por favor verificar el cambio.

**Comment by fredytellor** [comment]
ya esta lista el cambio 2.

**Comment by arias9306** [comment]
@JLancherosR  favor colocar las anotaciones de `@NotNull` a los campos requeridos en el model del usuario

**Comment by JLancherosR** [comment]
@arias9306 Anotaciones de NotNull y NotBlank a los campos requeridos usados.

**Comment by JLancherosR** [comment]
@arias9306 Anotaciones de NotNull y NotBlank para los campos requeridos hecha.

**Comment by JLancherosR** [comment]
La creación de usuarios funciona correctamente.
