### ISSUE TITLE
Consulta de Usuarios

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#7]
Opción de consulta de los usuarios registrados en el sistema, se debe mostrar en una tabla con la siguiente información: 

*

**Comment by fredytellor** [comment]
@arias9306  @EDIJAI @junior5200  por favor revisar que el modulo de la consulta de usuarios este funcionando bien, por favor comentar al terminar el testeo. si funciona por favor cerrar el problema.

**Comment by JLancherosR** [comment]
@lobo-93  por favor revisar que el modulo de la consulta de usuarios este funcionando bien, por favor comentar al terminar el testeo. si funciona por favor cerrar el problema.

**Comment by JLancherosR** [comment]
@lobo-93 por favor revisar que el modulo de la consulta de usuarios este funcionando bien, por favor comentar al terminar el testeo. si funciona por favor cerrar el problema.
