### ISSUE TITLE
Recordar Contraseña

### ISSUE THREAD

**Issue by arias9306** [arias9306/asignacion-cursos#9]
Opción en el login para que el usuario pueda recordar su contraseña, se debe de enviar un correo electrónico con una contraseña provisional para que el usuario pueda ingresar y al momento de ingresar se le debe solicitar que la cambie.. no puede avanzar hasta que la cambie

**Comment by fredytellor** [comment]
Funciona bien, se testeo delante del grupo.

**Comment by rcastellanos10** [comment]
Total de Horas dedicadas: 5 Horas
Desarrollo: 3 Horas
